// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm9hmY26jtcwqCObg2nF5mZrPSb8-_EV0',
    appId: '1:924262814822:web:906c0e60fefc16fafbc9a7',
    messagingSenderId: '924262814822',
    projectId: 'frnd-app-8c401',
    authDomain: 'frnd-app-8c401.firebaseapp.com',
    storageBucket: 'frnd-app-8c401.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJMhtw_DnuhzYDqfrA88zXHImgfDzMTFE',
    appId: '1:924262814822:android:e121392971a524bffbc9a7',
    messagingSenderId: '924262814822',
    projectId: 'frnd-app-8c401',
    storageBucket: 'frnd-app-8c401.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCddrrFduFJYm1M1R64SwReae5_ug8CGvw',
    appId: '1:924262814822:ios:df535c3ca3cd8f7efbc9a7',
    messagingSenderId: '924262814822',
    projectId: 'frnd-app-8c401',
    storageBucket: 'frnd-app-8c401.firebasestorage.app',
    iosBundleId: 'com.example.frndApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCddrrFduFJYm1M1R64SwReae5_ug8CGvw',
    appId: '1:924262814822:ios:df535c3ca3cd8f7efbc9a7',
    messagingSenderId: '924262814822',
    projectId: 'frnd-app-8c401',
    storageBucket: 'frnd-app-8c401.firebasestorage.app',
    iosBundleId: 'com.example.frndApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm9hmY26jtcwqCObg2nF5mZrPSb8-_EV0',
    appId: '1:924262814822:web:8eb9dcb57cfda30cfbc9a7',
    messagingSenderId: '924262814822',
    projectId: 'frnd-app-8c401',
    authDomain: 'frnd-app-8c401.firebaseapp.com',
    storageBucket: 'frnd-app-8c401.firebasestorage.app',
  );
}
